<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Customers Report - {{ $shop->name ?? 'Shop' }}</title>
    <style>
        @page { margin: 24px 22px; font-family: 'DejaVu Sans', Arial, sans-serif; }
        body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 10px; color: #000; }

        .header { border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 12px; }
        .header-left { display: inline-block; vertical-align: top; width: 64%; }
        .header-right { display: inline-block; vertical-align: top; width: 35%; text-align: right; }
        .header-logo { display: inline-block; vertical-align: top; width: 90px; }
        .header-info { display: inline-block; vertical-align: top; width: calc(100% - 95px); }
        .logo { max-width: 85px; max-height: 85px; object-fit: contain; }

        .inst-name { font-size: 14px; font-weight: 700; margin: 0 0 3px 0; }
        .inst-meta { font-size: 9px; line-height: 1.35; }
        .report-title { font-size: 12px; font-weight: 700; text-transform: uppercase; text-align: right; margin: 0 0 3px 0; }
        .report-sub { font-size: 9px; text-align: right; line-height: 1.35; }

        .section { margin-top: 14px; }
        .section-title { font-weight: 700; text-transform: uppercase; border-bottom: 2px solid #000; padding-bottom: 4px; margin-bottom: 6px; }

        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        th, td { border: 1px solid #000; padding: 6px; }
        th { background: #fff; font-weight: 700; text-align: left; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .muted { color: #555; }
        .page-break { page-break-after: always; }
    </style>
</head>
<body>

@php
  $shopName = $shop->name ?? 'Shop';
  $shopEmail = $shop->email ?? null;
  $shopPhone = $shop->phone ?? null;
  $shopAddress = $shop->address ?? null;
  $shopRegion = $shop->region ?? null;
  $shopCountry = $shop->country ?? null;
  $branchName = $subshop->name ?? 'Branch';
@endphp

<div class="header">
    <div class="header-left">
        <div class="header-logo">
            @if(!empty($shop->logo) && file_exists(public_path('storage/' . $shop->logo)))
                <img class="logo" src="{{ public_path('storage/' . $shop->logo) }}" alt="Logo">
            @endif
        </div>
        <div class="header-info">
            <div class="inst-name">{{ $shopName }}</div>
            <div class="inst-meta">
                @if($shopAddress)
                    <div><strong>Address:</strong> {{ $shopAddress }}</div>
                @endif
                @if($shopRegion || $shopCountry)
                    <div>
                        @if($shopRegion)<strong>Region:</strong> {{ $shopRegion }}@endif
                        @if($shopRegion && $shopCountry) | @endif
                        @if($shopCountry)<strong>Country:</strong> {{ $shopCountry }}@endif
                    </div>
                @endif
                @if($shopPhone)
                    <div><strong>Phone:</strong> {{ $shopPhone }}</div>
                @endif
                @if($shopEmail)
                    <div><strong>Email:</strong> {{ $shopEmail }}</div>
                @endif
            </div>
        </div>
    </div>

    <div class="header-right">
        <div class="report-title">Customers Report</div>
        <div class="report-sub">
            <div><strong>Branch:</strong> {{ $branchName }}</div>
            <div><strong>Generated:</strong> {{ now()->format('F j, Y \a\t g:i A') }}</div>
            <div><strong>Generated By:</strong> {{ $generatedBy ?? 'System' }}</div>
        </div>
    </div>
</div>

<div class="section">
    <div class="section-title">Summary KPIs</div>
    <table>
        <tr>
            <th>Metric</th>
            <th class="text-right">Value</th>
        </tr>
        <tr>
            <td>Total Customers</td>
            <td class="text-right">{{ number_format($summary['count'] ?? 0) }}</td>
        </tr>
        <tr>
            <td>Active Customers</td>
            <td class="text-right">{{ number_format($summary['active_count'] ?? 0) }}</td>
        </tr>
        <tr>
            <td>Inactive Customers</td>
            <td class="text-right">{{ number_format($summary['inactive_count'] ?? 0) }}</td>
        </tr>
        <tr>
            <td>Total Loans</td>
            <td class="text-right">{{ number_format($summary['total_loans'] ?? 0) }}</td>
        </tr>
        <tr>
            <td>Total Outstanding Balance</td>
            <td class="text-right">{{ number_format($summary['total_outstanding'] ?? 0, 2) }}</td>
        </tr>
        <tr>
            <td>Active Loans</td>
            <td class="text-right">{{ number_format($summary['total_active_loans'] ?? 0) }}</td>
        </tr>
        <tr>
            <td>Overdue Loans</td>
            <td class="text-right">{{ number_format($summary['total_overdue_loans'] ?? 0) }}</td>
        </tr>
        <tr>
            <td>Closed Loans</td>
            <td class="text-right">{{ number_format($summary['total_closed_loans'] ?? 0) }}</td>
        </tr>
        <tr>
            <td>Written Off Loans</td>
            <td class="text-right">{{ number_format($summary['total_written_off_loans'] ?? 0) }}</td>
        </tr>
    </table>
</div>

<div class="section">
    <div class="section-title">Customer Details</div>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Phone</th>
                <th>Gender</th>
                <th>Region</th>
                <th>Status</th>
                <th class="text-right">Total Loans</th>
                <th class="text-right">Outstanding Balance</th>
                <th class="text-right">Active Loans</th>
                <th class="text-right">Overdue Loans</th>
                <th class="text-right">Closed Loans</th>
                <th class="text-right">Written Off Loans</th>
                <th>Joined</th>
            </tr>
        </thead>
        <tbody>
            <?php $i=1; ?>
            @foreach ($rows as $e)
                <tr>
                    <td>{{ $i++ }}</td>
                    <td>{{ $e->name }}</td>
                    <td>{{ $e->phone ?? '-' }}</td>
                    <td>{{ $e->gender ?? '-' }}</td>
                    <td>{{ $e->region ?? '-' }}</td>
                    <td>{{ $e->is_active ? 'ACTIVE' : 'INACTIVE' }}</td>
                    <td class="text-right">{{ (int)($e->total_loans ?? 0) }}</td>
                    <td class="text-right">{{ number_format((float)($e->outstanding_balance ?? 0), 2) }}</td>
                    <td class="text-right">{{ (int)($e->active_loans ?? 0) }}</td>
                    <td class="text-right">{{ (int)($e->overdue_loans ?? 0) }}</td>
                    <td class="text-right">{{ (int)($e->closed_loans ?? 0) }}</td>
                    <td class="text-right">{{ (int)($e->written_off_loans ?? 0) }}</td>
                    <td>{{ optional($e->created_at)->format('Y-m-d') }}</td>
                </tr>
            @endforeach
            @if($rows->isEmpty())
                <tr>
                    <td colspan="14" class="text-center muted">No data available</td>
                </tr>
            @endif
        </tbody>
    </table>
</div>

</body>
</html>
