<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $subshopTitle ?? 'Shop' }} Inventory Ledger</title>
    <style>
        body { font-family: 'DejaVu Sans', Arial, sans-serif; margin:0; padding:15px; color:#333; font-size:10px; line-height:1.4; }
        .header { background:#2c3e50; color:#fff; padding:20px; text-align:center; margin-bottom:20px; }
        .header h1{ font-size:26px; margin:0 0 8px; font-weight:700; }
        .header .subtitle{ font-size:14px; margin:0 0 10px; }
        .header .meta{ margin-top:10px; font-size:9px; border-top:1px solid rgba(255,255,255,0.3); padding-top:10px; }
        .filters { font-size:9px; margin-top:6px; opacity:.95; }
        .filters span{ display:inline-block; margin: 0 6px; }
        .data-table{ width:100%; border-collapse:collapse; font-size:8px; margin-top:10px; table-layout: fixed; }
        .data-table thead th{ background:#34495e; color:#fff; padding:8px 4px; text-align:left; font-weight:700; font-size:8px; text-transform:uppercase; border:1px solid #2c3e50; }
        .data-table td{ padding:6px 4px; border:1px solid #ddd; vertical-align:top; word-wrap:break-word; }
        .data-table tbody tr:nth-child(odd){ background:#f9f9f9; }
        .data-table tbody tr:nth-child(even){ background:#fff; }
        .col-date{ width:14%; } .col-subshop{ width:12%; } .col-event{ width:10%; } .col-item{ width:18%; }
        .col-batch{ width:10%; } .col-qty{ width:8%; } .col-cost{ width:9%; } .col-retail{ width:9%; } .col-ref{ width:10%; }
        .footer { margin-top: 14px; padding: 8px; border-top: 1px solid #ddd; font-size: 9px; color: #666; text-align: center; }
        .muted { color:#555; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $subshopTitle ?? 'Shop' }}</h1>
        <div class="subtitle">INVENTORY LEDGER</div>
        <div class="filters">
            @if(!empty($filters['date_from']) || !empty($filters['date_to']))
                <span>Date: {{ $filters['date_from'] ?? '—' }} to {{ $filters['date_to'] ?? '—' }}</span>
            @endif
            @if(!empty($filters['event']))
                <span>Event: {{ strtoupper($filters['event']) }}</span>
            @endif
            @if(!empty($filters['category']))
                <span>Category: {{ $filters['category'] }}</span>
            @endif
            @if(!empty($filters['supplier']))
                <span>Supplier: {{ $filters['supplier'] }}</span>
            @endif
            @if(!empty($filters['item']))
                <span>Item: {{ $filters['item'] }}</span>
            @endif
        </div>
        <div class="meta">Generated: {{ now()->format('F j, Y \a\t g:i A') }} | System: DukaBase</div>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th class="col-date">DATE</th>
                <th class="col-subshop">SUBSHOP</th>
                <th class="col-event">EVENT</th>
                <th class="col-item">ITEM</th>
                <th class="col-batch">BATCH</th>
                <th class="col-qty">QTY +/-</th>
                <th class="col-cost">VALUE (COST)</th>
                <th class="col-retail">VALUE (RETAIL)</th>
                <th class="col-ref">REF</th>
            </tr>
        </thead>
        <tbody>
            @foreach(($rows ?? []) as $r)
            <tr>
                <td>{{ $r[0] }}</td>
                <td>{{ $r[1] }}</td>
                <td>{{ strtoupper($r[2]) }}</td>
                <td>{{ $r[3] }}</td>
                <td>{{ $r[4] }}</td>
                <td>{{ number_format((int)$r[5]) }}</td>
                <td>{{ number_format((float)$r[8], 2) }}</td>
                <td>{{ number_format((float)$r[9], 2) }}</td>
                <td>{{ $r[10] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Report generated by: <strong>{{ $generatedBy ?? 'System' }}</strong> • {{ now()->format('Y-m-d H:i:s') }}
    </div>
</body>
</html>
