<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Repayment Frequencies - {{ $subshop->name }}</title>
    <style>
        @page { margin: 24px 22px; font-family: 'DejaVu Sans', Arial, sans-serif; }
        body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 10px; color: #000; }
        .header { border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 12px; }
        .header-left { display: inline-block; vertical-align: top; width: 64%; }
        .header-right { display: inline-block; vertical-align: top; width: 35%; text-align: right; }
        .header-logo { display: inline-block; vertical-align: top; width: 90px; }
        .header-info { display: inline-block; vertical-align: top; width: calc(100% - 95px); }
        .logo { max-width: 85px; max-height: 85px; object-fit: contain; }
        .inst-name { font-size: 14px; font-weight: 700; margin: 0 0 3px 0; }
        .inst-meta { font-size: 9px; line-height: 1.35; }
        .report-title { font-size: 12px; font-weight: 700; text-transform: uppercase; text-align: right; margin: 0 0 3px 0; }
        .report-sub { font-size: 9px; text-align: right; line-height: 1.35; }
        .block-title { font-size: 10px; font-weight: 700; margin: 14px 0 6px 0; text-transform: uppercase; }
        .kpi { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .kpi td { border: 1px solid #000; padding: 7px 6px; }
        .kpi .kpi-label { font-size: 8px; font-weight: 700; text-transform: uppercase; }
        .kpi .kpi-value { font-size: 11px; font-weight: 700; margin-top: 2px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
        th, td { border: 1px solid #000; padding: 6px; }
        th { background: #fff; font-weight: 700; text-align: left; }
        td.num, th.num { text-align: right; }
        .page-break { page-break-before: always; }
        .footer { border-top: 1px solid #000; margin-top: 14px; padding-top: 6px; font-size: 8px; }
        .footer-left { display: inline-block; vertical-align: top; width: 70%; }
        .footer-right { display: inline-block; vertical-align: top; width: 29%; text-align: right; }
    </style>
</head>
<body>
    @php
        $shop = $subshop->shop ?? null;
        $shopName = $shop->name ?? $subshop->name ?? 'Institution';
        $shopEmail = $shop->email ?? null;
        $shopPhone = $shop->phone ?? null;
        $shopAddress = $shop->address ?? null;
        $shopLogo = $shop->logo ?? null;
        $generatedAt = now()->format('Y-m-d H:i:s');
    @endphp

    <div class="header">
        <div class="header-left">
            <div class="header-logo">
                @if(!empty($shopLogo) && file_exists(public_path('storage/' . $shopLogo)))
                    <img class="logo" src="{{ public_path('storage/' . $shopLogo) }}" alt="Logo">
                @endif
            </div>
            <div class="header-info">
                <div class="inst-name">{{ $shopName }}</div>
                <div class="inst-meta">
                    @if($shopAddress)
                        <div><strong>Address:</strong> {{ $shopAddress }}</div>
                    @endif
                    @if($shopPhone)
                        <div><strong>Phone:</strong> {{ $shopPhone }}</div>
                    @endif
                    @if($shopEmail)
                        <div><strong>Email:</strong> {{ $shopEmail }}</div>
                    @endif
                </div>
            </div>
        </div>
        <div class="header-right">
            <div class="report-title">Repayment Frequencies</div>
            <div class="report-sub">
                <div><strong>Branch:</strong> {{ $subshop->name }}</div>
                <div><strong>Generated:</strong> {{ $generatedAt }}</div>
                <div><strong>Generated By:</strong> {{ $generatedBy }}</div>
            </div>
        </div>
    </div>

    <table class="kpi">
        <tr>
            <td>
                <div class="kpi-label">Total Frequencies</div>
                <div class="kpi-value">{{ $summary['total'] ?? 0 }}</div>
            </td>
            <td>
                <div class="kpi-label">Active</div>
                <div class="kpi-value">{{ $summary['active'] ?? 0 }}</div>
            </td>
            <td>
                <div class="kpi-label">Inactive</div>
                <div class="kpi-value">{{ $summary['inactive'] ?? 0 }}</div>
            </td>
            <td>
                <div class="kpi-label">Month Based</div>
                <div class="kpi-value">{{ $summary['month_based'] ?? 0 }}</div>
            </td>
        </tr>
    </table>

    <div class="block-title">Repayment Frequencies List</div>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Code</th>
                <th>Name</th>
                <th>Interval Days</th>
                <th>Month Based</th>
                <th>Min Installments</th>
                <th>Max Installments</th>
                <th>Status</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($repaymentFrequencies as $index => $frequency)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $frequency->code }}</td>
                    <td>{{ $frequency->name }}</td>
                    <td>{{ $frequency->interval_days }} days</td>
                    <td>{{ $frequency->is_month_based ? 'Yes' : 'No' }}</td>
                    <td>{{ $frequency->min_installments ?? 'N/A' }}</td>
                    <td>{{ $frequency->max_installments ?? 'N/A' }}</td>
                    <td>{{ $frequency->is_active ? 'Active' : 'Inactive' }}</td>
                    <td>{{ $frequency->created_at->format('M d, Y') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="text-align:center; color:#777; padding:10px;">No repayment frequencies found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <div class="footer-left">
            <strong>{{ $shopName }}</strong> | Repayment Frequencies Report
        </div>
        <div class="footer-right">
            Page 1
        </div>
    </div>
</body>
</html>
